---
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: git://github.com/adrienverge/yamllint
    rev: v1.24.2
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        exclude: ^helm-charts
        entry: yamllint --strict
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        minimum_pre_commit_version: 2.4.0
        language: golang
        additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.1.1]
        entry: shfmt
        args: [-w]
        types: [shell]
  - repo: git://github.com/flaudisio/pre-commit-hooks
    rev: v0.8.0
    hooks:
      - id: hadolint
