---
version: '3.7'

services:
  web:
    build:
      context: ../backend
    image: backend:latest
    entrypoint: ["./init.sh"]
    volumes:
      - ./init.sh:/home/app/web/init.sh
    command: ["/usr/local/bin/uwsgi", "--ini", "uwsgi.ini"]
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
